config/routes.rb
Rails.application.routes.draw do
  resources :buses
  resources :sptrans
  get 'bus_stops/search_for_bus_stop', to: 'bus_stops_controller#search_for_bus_stop'
  post 'bus_stops/search_for_bus_stop', to: 'bus_stops#search_for_bus_stop'
  get 'bus_stops/show/:id/cl/:cl/px/:px/py/:py' => "id#cl#px#py", :as => :id
  post 'bus_stops/show'
  get 'bus_stops/index'
  root 'bus_stops#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/SPTrans/http_client_configuration.rb
module SPTrans
  module HttpClientConfiguration
    private

    def base_url
      # TODO
      "http://api.olhovivo.sptrans.com.br/v2.1/"
    end

    def auth_header
      { 'access-token' => #TOKEN }
    end

    def basic_headers
      { 'User-Agent' => 'dencity',
        'Content-Type' => 'application/json',
        'Accept' => 'application/json' }.merge(auth_header)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bus.rb
module Bus
  class << self
    attr_accessor :configuration
  end

  def self.configure
    self.configuration ||= Bus::Configuration.new
    yield(configuration)
  end
end

app/models/bus/configuration.rb
module Bus
  class Configuration
    attr_accessor :base_url
  end
end

app/models/bus/http_client_configuration.rb
module Bus
  module HttpClientConfiguration
    private

    def base_url
      Bus.configuration.base_url
    end

    def auth_header
      {}
    end

    def basic_headers
      { 'User-Agent' => 'dencity',
        'Content-Type' => 'application/json',
        'Accept' => 'application/json' }.merge(auth_header)
    end
  end
end

app/models/sptrans.rb
module Sptrans
  class << self
    attr_accessor :configuration
  end

  def self.configure
    self.configuration ||= Sptrans::Configuration.new
    yield(configuration)
  end
end

app/models/sptrans/configuration.rb
module Sptrans
  class Configuration
    attr_accessor :base_url
    attr_accessor :token
  end
end

app/models/sptrans/http_client_configuration.rb
module Sptrans
  module HttpClientConfiguration
    private

    def base_url
      Sptrans.configuration.base_url
    end

    def auth_header
      { 'access-token' => Sptrans.configuration.token }
      # { 'set-cookie' => ''}
    end

    def basic_headers
      { 'User-Agent' => 'dencity',
        'Content-Type' => 'application/json',
        'Accept' => 'application/json' }.merge(auth_header)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bus_stops_controller.rb
require 'net/http'
require 'cgi'

class BusStopsController < ApplicationController
  include Resources::HttpClient
  include ::Sptrans::HttpClientConfiguration

  def index
  end

  def search_for_bus_stop
    termosBusca = params[:bus_stop_address]
    bus_stop_info_json = get(url: "", params: { termosBusca: termosBusca, api: "PARADAS" })
    @lines = JSON.parse bus_stop_info_json.body
    render bus_stops_search_for_bus_stop_path
  end

  class << self
    include Resources::HttpClient
    include ::Sptrans::HttpClientConfiguration
    def search_for_line(line, prefix)
      termosBusca = line
      bus_info = get(url: "", params: { termosBusca: termosBusca, api: "LINHAS" })
      buses = JSON.parse bus_info.body
      # buses['vs'].each do |bus|
        # if bus['p'] == prefix
          # return bus
      # end
    # end
    return buses
    end
  end
end

app/controllers/buses_controller.rb
require 'net/http'
require 'cgi'

class BusesController < ApplicationController
  include Resources::HttpClient
  include ::Bus::HttpClientConfiguration

  # GET /buses
  # GET /buses.json
  def index
    # @buses = Bus.all
  end

  # GET /buses/1
  # GET /buses/1.json
  def show
    id = params[:id]
    cl = params[:cl] # código identificador único da linha
    @name = params[:name]
    # get info from endpoint
    @bus_info = get(url: "buses", params: { id: id })
    @bus_info = JSON.parse @bus_info.body
    @bus_info = @bus_info

    #get info from sptrans
    @bus_sptrans = BusStopsController.search_for_line(cl, id)
    # TODO
    # plotar localização do bus no ônibus
    # exibir lotação
    @bus = nil
  end

  # GET /buses/new
  def new
    @bus = Bus.new
  end

  # GET /buses/1/edit
  def edit
  end

  # POST /buses
  # POST /buses.json
  def create
    @bus = Bus.new(bus_params)

    respond_to do |format|
      if @bus.save
        format.html { redirect_to @bus, notice: 'Bus was successfully created.' }
        format.json { render :show, status: :created, location: @bus }
      else
        format.html { render :new }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buses/1
  # PATCH/PUT /buses/1.json
  def update
    respond_to do |format|
      if @bus.update(bus_params)
        format.html { redirect_to @bus, notice: 'Bus was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus }
      else
        format.html { render :edit }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buses/1
  # DELETE /buses/1.json
  def destroy
    @bus.destroy
    respond_to do |format|
      format.html { redirect_to buses_url, notice: 'Bus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search_load
    bus_load = Bus.find_by(id:@bus)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus
      @bus = Bus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bus_params
      params.require(:bus).permit(:prefix, :line, :load, :arrival_time, :py, :px)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bus_stop_helper.rb
module BusStopHelper
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/views/bus_stop/index.html.erb
<h1><%= @teste %>, buceta</h1>
<div class="container">
  <%= form_tag bus_stop_search_for_bus_stop_path({class: 'form-group'}) do %>
  <div class="row">
    <div class="col-xs-12">
      <p> Digite o endereço do ponto de ônibus: </p>
    </div>
  <div class="row">
    <div class="col-xs-9">
      <%= text_field_tag :bus_stop_address, "", placeholder: "Endereço", class: "form-control"%>
    </div>
    <div class="col-xs-3">
      <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
        Buscar <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
    </div>
  </div>
  </div>
    <% end %>
 <% end %>
  </div>
</div>

<div id="map", style="height: 500px;">
</div>

app/views/bus_stops/index.html.erb
<div class="container">
  <%= form_tag bus_stops_search_for_bus_stop_path do %>
  <div class="row">
    <div class="col-xs-12">
      <p> Digite o endereço do ponto de ônibus: </p>
    </div>
  <div class="row">
    <div class="col-xs-9">
      <%= text_field_tag 'bus_stop_address', "", placeholder: "Endereço", class: "form-control" %>
    </div>
    <div class="col-xs-3">
      <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
        Buscar <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
    </div>
  </div>
  </div>
    <% end %>
 <% end %>
  </div>
</div>
<br>
<div id="map", style="height: 500px;">
</div>

app/views/bus_stops/search_for_bus_stop.html.erb
<p id="notice"><%= notice %></p>

<h3>Linhas que atendem este ponto</h3>
<h6>Momento da consulta: <b><%= @lines['hr']%></b></h6>
<% if @lines['p'].nil? %>
  Nenhuma linha encontrada com ônibus circulando no ponto pesquisado.
<% else %>
  <table>
    <thead>
      <tr>
        <th style="padding:0 15px 0 15px;">Linha</th>
        <th>Letreiro</th>
        <th>Horário Previsto</th>
      </tr>
    </thead>

    <tbody>
      <% @lines['p']['l'].each do |b| %>
        <tr>
          <td><%= b['c'] %></td>
          <% if b['qv'] >= 1 %>
            <td><%= link_to(b['lt0'], bus_path(Integer(b['vs'][0]['p']), cl: Integer(b['cl']), px: b['vs'][0]['px'], py: b['vs'][0]['py'], name: b['lt0']), method: :get) %></td>
            <td><%= b['vs'][0]['t'] %></td>
          <% else %>
            <td><%= b['lt0'] %></td>
            <td>Nenhum ônibus circulando.</td>
          <% end %>
        </tr>

        <tr>
          <td><%= b['c'] %></td>
          <% if b['qv'] >= 1 %>
            <td><%= link_to(b['lt1'], bus_path(Integer(b['vs'][0]['p']), cl: Integer(b['cl']), px: b['vs'][0]['px'], py: b['vs'][0]['py'], name: b['lt1']), method: :get) %></td>
            <td><%= b['vs'][0]['t'] %></td>
          <% else %>
            <td><%= b['lt1'] %></td>
            <td>Nenhum ônibus circulando.</td>
          <% end %>
        </tr>
        <% end %>
      <% end %>
  </tbody>

app/views/buses/_form.html.erb
<%= form_with(model: bus, local: true) do |form| %>
  <% if bus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bus.errors.count, "error") %> prohibited this bus from being saved:</h2>

      <ul>
      <% bus.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :prefix %>
    <%= form.text_field :prefix %>
  </div>

  <div class="field">
    <%= form.label :line %>
    <%= form.text_field :line %>
  </div>

  <div class="field">
    <%= form.label :load %>
    <%= form.text_field :load %>
  </div>

  <div class="field">
    <%= form.label :arrival_time %>
    <%= form.text_field :arrival_time %>
  </div>

  <div class="field">
    <%= form.label :py %>
    <%= form.text_field :py %>
  </div>

  <div class="field">
    <%= form.label :px %>
    <%= form.text_field :px %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buses/edit.html.erb
<h1>Editing Bus</h1>

<%= render 'form', bus: @bus %>

<%= link_to 'Show', @bus %> |
<%= link_to 'Back', buses_path %>

app/views/buses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buses</h1>

<table>
  <thead>
    <tr>
      <th>Prefix</th>
      <th>Line</th>
      <th>Load</th>
      <th>Arrival time</th>
      <th>Py</th>
      <th>Px</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @buses%>
      <% @buses.each do |bus| %>
        <tr>
          <td><%= bus.prefix %></td>
          <td><%= bus.line %></td>
          <td><%= bus.load %></td>
          <td><%= bus.arrival_time %></td>
          <td><%= bus.py %></td>
          <td><%= bus.px %></td>
          <td><%= link_to 'Show', bus %></td>
          <td><%= link_to 'Edit', edit_bus_path(bus) %></td>
          <td><%= link_to 'Destroy', bus, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% else %>
    puts man
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bus', new_bus_path %>

app/views/buses/new.html.erb
<h1>New Bus</h1>

<%= render 'form', bus: @bus %>

<%= link_to 'Back', buses_path %>

app/views/buses/show.html.erb
<p id="notice"><%= notice %></p>
<% if @bus_info.nil? || @bus_info.count == 0 %>
  Não há informações sobre a lotação do ônibus buscado.
<% else %>
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h4><%= @bus_info['line'].to_s %> - <%= @name %></h4>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-6">
        <b>Prefixo do ônibus:</b>
      </div>
      <div class="col-xs-6">
        <%= @bus_info['prefix'] %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-6">
        <b>Lotação:</b>
      </div>
      <div class="col-xs-6">
          <% if @bus_info['load'].to_i < 38 %>
            <b style="color:green;">Vazio</b>
          <% elsif @bus_info['load'].to_i >= 38 && @bus_info['load'].to_i < 75 %>
            <b style="color:blue;">Alguns lugares vagos</b>
          <% elsif @bus_info['load'].to_i >= 75 && @bus_info['load'].to_i < 112 %>
            <b style="color:yellow;">Cheio</b>
          <% else %>
            <b style="color:red;">Lotado</b>
          <% end %>

      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <b>Localização do ônibus:</b>
      </div>
    </div>
  </div>
  <div id="map" style="width:100%;height: 400px;"></div>
  <script>
  // Initialize and add the map
  function initMap() {
    var url_string = window.location.href;
    var url = new URL(url_string);
    var px = parseFloat(url.searchParams.get("px"));
    var py = parseFloat(url.searchParams.get("py"));

    // The location of Uluru
    var uluru = {lat: py, lng: px};
    // The map, centered at Uluru
    var map = new google.maps.Map(
        document.getElementById('map'), {zoom: 15, center: uluru});
    // The marker, positioned at Uluru
    var marker = new google.maps.Marker({position: uluru, map: map});
  }
  </script>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dencity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCtqlIxNOdmhZSxVdc9NiC_G_64EFqzF3k&callback=initMap" async defer> </script>
    <meta name="viewport" content="width=370, initial-scale=1.0">

    </head>

  <body style="background: #A9BCF5;">
    <div class="container">
      <div class="row">
      <div class="col-xs-2"><br /><%= link_to root_path do %>
                                    <%= image_tag("logoDencity.png", alt: "Logo", width:50) %></div>
                                  <% end %>
      <div class="col-xs-10"> <h1><%= link_to('Dencity', root_path, {style: 'color:black;text-decoration: none;'}) %></h1> </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>